# Form implementation generated from reading ui file 'testNoxxicUI.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import NoxxicScraper
import time
import os

from os import wait
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def OnPushButton(self):
        self.openWeightValues.hide()
        self.resultLabel.setStyleSheet("color: ;")
        self.progressBar.setProperty("value", 0)
        self.progressBar.show()
        self.resultLabel.setText("Getting classes from wowwiki")
        QtWidgets.QApplication.processEvents()
        time.sleep(1)

        self.progressBar.setProperty("value", 10)
        QtWidgets.QApplication.processEvents()
        time.sleep(1)
        NoxxicScraper.GetClasses()
        self.progressBar.setProperty("value", 20)
        QtWidgets.QApplication.processEvents()
        time.sleep(1)
        self.resultLabel.setText("Getting stats from Noxxic")
        QtWidgets.QApplication.processEvents()
        time.sleep(1)

        NoxxicScraper.GetNoxxicStats()
        self.progressBar.setProperty("value", 40)
        QtWidgets.QApplication.processEvents()
        time.sleep(1)
        self.resultLabel.setText("Creating WeightValues.lua file")
        QtWidgets.QApplication.processEvents()
        time.sleep(1)

        self.progressBar.setProperty("value", 50)
        QtWidgets.QApplication.processEvents()
        time.sleep(1)
        NoxxicScraper.CreateWeightValuesFile()
        self.progressBar.setProperty("value", 60)
        QtWidgets.QApplication.processEvents()
        time.sleep(1)
        self.resultLabel.setText("Checking differences")
        QtWidgets.QApplication.processEvents()
        time.sleep(1)

        self.progressBar.setProperty("value", 70)
        QtWidgets.QApplication.processEvents()
        time.sleep(1)
        diff = NoxxicScraper.CheckDiff()
        self.progressBar.setProperty("value", 80)
        QtWidgets.QApplication.processEvents()
        time.sleep(1)
        self.resultLabel.setText("Removing unused files")
        QtWidgets.QApplication.processEvents()
        time.sleep(1)

        self.progressBar.setProperty("value", 90)
        QtWidgets.QApplication.processEvents()
        time.sleep(1)
        NoxxicScraper.RemoveUnusedFiles()
        self.progressBar.setProperty("value", 100)
        if diff:
            self.resultLabel.setText("There is some differencies")
            self.resultLabel.setStyleSheet("color: rgb(0, 255, 0);")
        else:
            self.resultLabel.setText("There is no differencies")
            self.resultLabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.openWeightValues.show()

    def OpenWeightValues(self):
        os.system("code WeightValues.lua")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startScanButton = QtWidgets.QPushButton(self.centralwidget)
        self.startScanButton.setGeometry(QtCore.QRect(145, 150, 110, 30))
        self.startScanButton.setObjectName("startScanButton")
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(20, 40, 360, 45))
        self.resultLabel.setMaximumSize(QtCore.QSize(400, 300))
        self.resultLabel.setStyleSheet("")
        self.resultLabel.setText("")
        self.resultLabel.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.resultLabel.setObjectName("resultLabel")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(100, 180, 200, 25))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.hide()
        self.openWeightValues = QtWidgets.QPushButton(self.centralwidget)
        self.openWeightValues.setGeometry(QtCore.QRect(140, 200, 115, 32))
        self.openWeightValues.setObjectName("openWeightValues")
        self.openWeightValues.hide()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.startScanButton.clicked.connect(self.OnPushButton)
        self.openWeightValues.clicked.connect(self.OpenWeightValues)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startScanButton.setText(_translate("MainWindow", "Start Scan"))
        self.openWeightValues.setText(_translate("MainWindow", "Open stats"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
